# original_text = """


# 1.	ALL NEGOS/EVENTUAL FIXTURE TO BE KEPT P AND C

# 2.	ACCOUNT: JSW STEEL LIMITED OR NOMINEE. (NOMINEES LIST APPENDED BELOW)

# 3.	CP CHAIN		: TO BE PROVIDED AT THE TIME OF NOMINATION OF PERFORMING VESSEL

# 4.	OWNERS 		: TO BE PROVIDED AT THE TIME OF NOMINATION OF PERFORMING VESSEL

# 5.	DISPONENT OWNERS	:
# # ATHENA SHIPPING PTE LTD,
# # 07 16 CENDEX CENTRE 120 LOWER DELTA ROAD
# #SINGAPORE 169208 SINGAPORE


# 6.	FREIGHT BENEFICARY WITH BANKING DETAILS:
# # ATHENA SHIPPING PTE LTD
# # BANK NAME: NATIONAL BANK OF FUJAIRAH.
# # BENEFICIARY ACCOUNT NUMBER: 012001525032
# # BENEFICIARY ADDRESS: #07-16, CENDEX CENTRE, 120 LOWER DELTA ROAD, SINGAPORE
# # 169208. ACCOUNT CURRENCY: USD ACCOUNT CATEGORY: CURRENT ACCOUNT CORPORATE
# # BRANCH: DUBAI IBAN: AE820380000012001525032 SWIFT CODE: NBFUAEAFDXB
# # CORRESPONDENT BANK: JP MORGAN CHASE BANK, NEW YORK, CHASUS33


# 7.	CP CHAIN TO BE PROVIDED BY OWNERS AT THE TIME OF FIRM OFFER.

# 8.	NAME AND ORIGIN OF COUNTRY OF THE FREIGHT BENEFICIARY AND PARTY SIGNING THE CHARTER PARTY SHOULD BE SAME.

# 9.	FOLLOWING OWNERS SHOULD NOT BE EVEN PART OF CP CHAIN:
# ##
# #I)	M/S NAVINYA SHIPPING SERVICES PVT LTD
# #II)	M/S SIMTRA INERNATIONAL FACE
# #III)	M/S NAVIN TRANSPORT
# #IV)	M/S WESTERN BULK CARRIER
# #V)	M/S JOHANN MK BLUEMENTHAL GMBH AND CO KG
# #VI)	M/S PHAETHON INTERNATIONAL CO SA
# #VII)	M/S HANSSY SHIPPING PTE LTD
# #VIII)	M/S SHANGHAI HENGXIN SHIPPING CO LTD
# #IX)	M/S TERA PROJECTS & SHIPPING SDN BHD
# #X)	M/S.SEATECH SHIPPING AND PROJECTS LTD
# #XI)	M/S.ALLIED SHIPPING
# #XII)	M/S.VICTORY SHIPPING
# #XIII)	M/S.HANNARA SHIPPING
# #XIV)	M/S.IAN SHIPPING
# #XV)	ANY CHINESE VESSEL OPERATORS AND/OR VESSEL OWNERS OF CHINA, AS DEFINED UNDER USTR GUIDELINES

# 10.	CARGO     	: COKING COAL 1 OR 2 GRADES IN BULK

# 11.	 QTY        	: 75000 MTS 10 PCT MOLOO

# 12.	LAYCAN		:  01-10 JUNE 2025

# ## IF VESSEL IS OUT OF LAY CAN, CHARTERERS HAVE AN OPTION TO CANCEL THE FIXTURE AND BOOK ANOTHER VESSEL FROM THE MARKET. ANY FREIGHT AND DEMURRAGE RATE DIFFERENTIAL WILL BE DEBITED / RECOVERED FROM OWNERS / BROKERS WITH WHOM THE FIXTURE HAS BEEN CANCELLED.

# 13.	  FULL DESCRIPTION OF THE VESSEL
# #A)	VESSEL TO BE RIGHTSHIP APPROVED.
# #B)	NOMINATED VESSEL SHALL BE GEARLESS KAMSARMAX/ PANAMAX SINGLE DECK BULK CARRIER CLASSED HIGHEST LLOYDS 100 A1 OR EQUIVALENT AND MAX 15 YEARS AGE TILL COMPLETION OF VOYAGE. CHARTERERS WILL NOT TAKE ANY RUSSIAN CALLER VESSEL WHICH HAS CALLED RUSSIA/RUSSIAN PORTS IN THE PAST FOR ANY SANCTIONED/OR NON-SANCTIONED CARGO).
# #C)	NOMINATED VESSEL SHOULD NOT BE BLACKLISTED BY ANY TERMINAL OR ANCHORAGES IN LOAD /DISPORTS.
# #D)	OWNERS TO NOMINATE VESSEL ALONG WITH VESSELS ALL VALID CERTIFICATES.
# #E)	VESSEL NOT TO BE OWNED BY IRAN/RUSSIAN/CIS/NORTH KOREAN OWNERS.
# #F)	 VESSEL HAS NEVER BEEN OWNED /OPERATED BY IRAN/NORTH KOREA OWNERS.
# #G)	VESSEL/VESSEL OWNER/OPERATOR/CARRIER/AGENTS IN THE CONTRACT CHAIN AGAINST USA OFAC REGULATION TO BE NOT ACCEPTABLE.
# #H)	VESSEL HAS NEVER BEEN CALLING AT ANY PORTS IN IRAN/NORTH KOREA OR IN NORTH KOREA WATER EVEN IF FOR BUNKERING.
# #I)	 NON ISRAILI, NON- IRANIAN AND NON- N KOREAN FLAG.
# #J)	NO RUSSIAN CALLER.
# #K)	MAX 15 YEARS OF AGE TILL COMPLETION.

# 14.	LOAD PORT		:   1SP 1/2 SB MCDUFFIE TERMINAL, MOBILE, ALABAMA, USA

# 15.	LOAD RATE:  AT ALL LOAD PORTS, THE CARGO SHALL BE LOADED AND TRIMMED (AS PER THE CUSTOM OF THE LOADING FACILITIES) FREE OF RISK AND EXPENSE TO THE VESSEL AT THE AVERAGE DAILY RATE OF 25,000 METRIC TONS PER WEATHER WORKING DAY OF 24 CONSECUTIVE HOURS SUNDAYS AND HOLIDAYS INCLUDED (SHINC) BUT EXCLUDING ANY STATE/TERMINAL 'SUPER HOLIDAYS', UNLESS USED (UU), IN WHICH CASE ACTUAL TIME USED TO COUNT (ATUTC).

# 16.	TURN TIME AT LOAD PORT	: 12 HRS TT UNLESS SOONER COMMENCE
# ## NOTICE OF READINESS (NOR) AT LOAD PORT: NOR TO BE TENDERED IN WRITING (TELEX, FAX CABLE, OR EMAIL) TO LOADING PORT AGENTS WITH COPY TO CHARTERERS AND BROKERS AT ANY TIME ON ANY DAY, SATURDAYS, SUNDAYS AND HOLIDAYS INCLUDED (SSHINC) BUT NEVER PRIOR TO THE BEGINNING OF THE LAYCAN AND EXCLUDING ON ANY ‘SUPER HOLIDAYS’ SET FORTH IN THE LOADING PORT RULES AND REGULATIONS, AFTER THE VESSEL HAS ARRIVED WITHIN THE LOADING PORT AND IS SECURED ALONGSIDE THE LOADING TERMINAL/BERTH OR ANCHORAGE PROVIDED THE VESSEL IS IN FREE PRATIQUE, CUSTOMS AND IMMIGRATION CLEARED AND IS READY IN ALL OTHER RESPECTS TO LOAD THE CARGO.
# ## NOR TO BE TENDERED AS PER THE LAYCAN PROVIDED AND ANY NOR TENDERED BEFORE OR AFTER THE AGREED LAYCAN IS INVALID. IF VESSEL TENDERS THE NOR AFTER THE LAYCAN THEN LAYTIME TO COMMENCE UPON COMMENCEMENT OF LOADING.
# ## IF THE VESSEL IS ORDERED BY ANY GOVERNMENTAL AUTHORITY TO ANCHOR OFF THE COAST FOR ANY REASON, THEN THE NOTICE OF READINESS CANNOT BE TENDERED TO THE CHARTERERS UNTIL THE VESSEL HAS BEEN CLEARED BY SUCH AUTHORITY TO ENTER THE LOAD PORT. IF THE GOVERNMENTAL AUTHORITY REQUIRES THE VESSEL TO ENTER THE PORT FOR INSPECTION, THEN THE NOR CAN ONLY BE TENDERED TO THE CHARTERERS AFTER THE VESSEL HAS BEEN CLEARED BY THE GOVERNMENTAL AUTHORITY REQUIRING SUCH CLEARANCE.
# ## IN THE EVENT OF CONGESTION OR FOR REASONS THAT OWNERS/VESSEL/MASTER ARE NOT RESPONSIBLE, THE VESSEL IS UNABLE TO TENDER ITS N.O.R. AS AGREED, THEN THE VESSEL MAY TENDER ITS N.O.R. ON ARRIVAL AT THE CUSTOMARY WAITING ANCHORAGE/BERTH (AS DIRECTED BY PILOTS/RELEVANT AUTHORITY) WHETHER IN PORT (OR TERMINAL) OR NOT (WIPON), (PROVIDED HE IS UNABLE TO ENTER TO WITHIN SAME), WHETHER IN BERTH OR NOT (WIBON), WHETHER IN FREE PRATIQUE OR NOT (WIFPON), WHETHER ENTERED CUSTOMS/IMMIGRATION CLEARED OR NOT (WECON), AND TIME TO COUNT AS AGREED. IF HOWEVER, IMMEDIATELY ON BERTHING THE VESSEL IS FOUND NOT TO BE READY IN ALL RESPECTS TO LOAD THE CARGO, THEN N.O.R. IS DEEMED TO BE NULL AND VOID, AND A NEW N.O.R. IS TO BE TENDERED ONCE THE VESSEL IS DEEMED READY IN ALL RESPECTS TO LOAD, AND TIME IS TO THEN TO COUNT AS AGREED, IRRESPECTIVE OF WHETHER THE VESSEL IS ON DEMURRAGE OR NOT; ANY TIME USED FOR GAINING FREE PRATIQUE OR CUSTOMS/IMMIGRATION CLEARANCE IS NOT TO COUNT AS LAYTIME OR TIME ON DEMURRAGE.
# ## VESSEL IS NOT TO TENDER VESSEL'S N.O.R. PRIOR TO LAST GIVEN E.T.A. LOAD PORT NOTICE.
# ## IF N.O.R. IS TENDERED DURING AN EXCLUDED PERIOD, THEN N.O.R. SHALL BE DEEMED TO HAVE BEEN TENDERED AT 09:00HOURS THE NEXT WORKING DAY, OR WHENEVER SAID EXCLUDED PERIOD (SUPER HOLIDAY) ENDS, WHICHEVER THE SOONER.

# 17.	DISCHARGE PORT- 1/2 SP 1/2SB – (GOA, NEW MANGALORE, JAIGARH, ENNORE, KRISHNAPATNAM, PARADIP) IN CHARTERER’S OPTION. ANY OTHER DISPORT ON OPEN BOOK BASIS.

# 18.	DISCHARGE RATE-
# # 25000 MT PWWD SHINC – (GOA / ENNORE/ NEW MANGALORE/ KRISHNAPATNAM/ JAIGARH/ PARADIP). EXCLUDING LOCAL SUPER HOLIDAYS # AS PER TERMINAL RULES

# 19.	NOTICE OF READINESS AT DISCHARGE PORT:
# NOTICE OF READINESS (“NOR”) TO BE TENDERED AT THE DISCHARGE PORT BY FAX OR EMAIL, TO THE ADDRESS PROVIDED BY CHARTERERS WHEN THE VESSEL ARRIVES AT THE CUSTOMARY ANCHORAGE OR AWAITING AREA OF THE DISCHARGE PORT OR, IF THE VESSEL MOVES DIRECTLY TO THE BERTH, WHEN THE VESSEL IS SECURELY MOORED AT THE BERTH, BEING AT ANY TIME IN OR OUT OF OFFICE HOURS, SATURDAYS, SUNDAYS AND PUBLIC HOLIDAYS INCLUDED, IRRESPECTIVE OF WHETHER OR NOT FREE PRATIQUE HAS BEEN GRANTED, THE VESSEL HAS THE NECESSARY ISPS CLEARANCE, IS GAS FREE, OR IS IN ALL RESPECTS READY TO DISCHARGE THE CARGO.


# 20.	TURN TIME AT DISCHARGE PORT - 12 HRS TT UNLESS SOONER COMMENCE (USC) AT EACH DISPORT(S).

# 21.	ETA NOTICES: OWNERS / MASTER TO TENDER REGULAR AND MANDATORY 15/14/ 13/12/10 / 7 / 5 / 3 / 2 / 1 DAYS & 12 HRS NOTICES TO SHIPPERS/CHRTRS/ LOAD/DSCH PORT AGENTS.
# ## OWNERS TO FOLLOW LOADPORT /DISCHARGE TERMINAL RULES AND REGULATIONS.


# 22.	NOMINATION: OWNERS TO NOMINATE PERFORMING VESSEL 15 DAYS PRIOR TO FIRST DAY OF LAYCAN. IN CASE OF SUBSTITUTION, PERFORMING VESSEL OF A SIMILAR SIZE TO BE NOMINATED 10 DAYS PRIOR TO FIRST DAY OF LAYCAN AND VESSEL ETA LOAD PORT WITHIN THE AGREED LAYCAN AND VESSEL ETA SHOULD NOT BE EARLIER THAN THE INITIAL VESSEL NOMINATION. CHARTERERS TO CONFIRM SUBSTITUTE VESSEL ACCEPTANCE/REJECTION WITHIN 48 HOURS. OWNERS TO PROVIDE STOWAGE PLAN CONSIDERING DRAFT RESTRICTION BOTH ENDS ALONG WITH VESSEL NOMINATION/ SUBSTITUTION AS PER TERMS AGREED. CHARTERERS TO PROVIDE VESSEL ACCEPTANCE ONLY UPON RECEIPT OF PRE-STOWAGE PLAN. OWNERS SHALL PROVIDE STOWAGE PLAN NO LATER THAN 5 DAYS PRIOR TO ETA OF THE VESSEL AND PROVIDE SUCH OTHER PRE ARRIVAL DOCUMENTATION IS REQUIRED UNDER LOAD PORT RULES & REGULATIONS.

# ## IN EACH CASE, THE VESSEL NOMINATED BY OWNER SHALL COMPLY WITH THE VESSEL SUITABILITY REQUIREMENTS SET FORTH IN THE LOADING PORT RULES AND REGULATIONS, AND ANY COSTS AND EXPENSES RELATING TO THE LOADING PORT’S DENIAL OF THE VESSEL FOR FAILURE TO MEET THESE REQUIREMENTS SHALL BE FOR OWNER’S ACCOUNT.  OWNER’S NOMINATION SHALL SPECIFY THE VESSEL’S PARTICULARS, INCLUDING THE NAME OF THE VESSEL, DEADWEIGHT, LENGTH OVERALL, ARRIVAL DRAUGHT, ESTIMATED LOADED DRAUGHT, NUMBER OF HATCHES, HOLDS AND HATCH DIMENSIONS AND OTHER INFORMATION CHARTERER MAY REASONABLY REQUIRE TO ENSURE THAT THE NOMINATED VESSEL IS SUITABLE IN ALL RESPECTS TO PERFORM THE TRANSPORTATION OF THE COAL IN ACCORDANCE WITH THE REQUIREMENTS OF THIS AGREEMENT

# ## OWNERS SHALL COMPLY WITH THE LOADING REQUIREMENTS SET FORTH IN THE LOADING PORT RULES AND REGULATIONS INCLUDING DE-BALLASTING AND TRIMMING REQUIREMENTS.
# THE VESSEL’S MASTER /AGENTS SHALL SUBMIT A FINAL LOAD PLAN (AS THAT TERM MAY BE DEFINED IN THE LOADING PORT RULES AND REGULATIONS) AT LEAST 48 HRS PRIOR TO THE VESSEL BERTHING WHICH SHALL BE SUBJECT TO THE APPROVAL OF THE LOADING PORT.

# ## QTY LOADABLE BSS 14 MTR DISPORT ARRIVAL DRAFT GOA (AS BASE) TO BE FINAL AND BINDING TO ASCERTAIN THE DEAD FREIGHT QTY IF ANY, IRRESPECTIVE OF DISPORT SECELCTED TO DISCHARGE THE VESSEL. ALSO, TO PROVIDE FOLLOWING SET OF THE SHIP’S DOCUMENTS FOR OBTAINING SHIPPER'S APPROVAL. A)  THE RIGHTSHIP QUESTIONNAIRE FULLY COMPLETED. B)  THE RIGHTSHIP STAR RATING CERTIFICATE.

# 23.	LAYTIME AT LOAD PORT - SHALL COMMENCE TWELVE (12) CONSECUTIVE HOURS (THE “TURN TIME” USC) AFTER NOTICE OF READINESS HAS BEEN ACCEPTED.
# # OWNER AGREES AND ACCEPTS THE PORT OF LOADING, HAVING INVESTIGATED FOR ITSELF THE SUITABILITY AND SAFENESS OF THE BERTHS. OWNER UNDERSTANDS THAT CHARTERER DOES NOT OWN, OPERATE, OR CONTROL THE PORT OF LOADING, AND CHARTERER HEREBY DISCLAIMS ANY WARRANTIES OF SAFE BERTH. OWNER ACCEPTS THE RISK OF THE PORT OF LOADING. IF LAY-BERTH IS ORDERED BY THE TERMINAL’S MANAGEMENT, SAME TO BE FOR VESSEL EXPENSE AS PER THE ALABAMA STATE PORT AUTHORITY’S (ASPA) TARIFF.

# 24.	THE FOLLOWING CONDITIONS SHALL APPLY IN RESPECT OF TURN TIME AND LAY-TIME AT LOAD AND / OR DISCHARGE PORTS-
# #A. TURN TIME SHALL MEAN THE TWELVE (12) HOUR TIME PERIOD PROVIDED TO THE LOADING OR DISCHARGE PORT THAT WILL PRECEDE THE START OF LAY-TIME. TURN TIME WILL COMMENCE UPON THE CHARTERER’S ACCEPTANCE OF NOTICE OF READINESS (N.O.R.). AFTER THE EXPIRATION OF TURN TIME, FOR THE FIRST SHIFTING ONLY, ANY TIME USED TO MOVE THE VESSEL FROM ANCHORAGE TO BERTH SHALL NOT COUNT AS LAY-TIME BENDS.
#  #B. LAY-TIME SHALL MEAN THE PERIOD OF TIME AGREED UPON TO ALLOW FOR THE CARGO TO BE LOADED/UNLOADED ONBOARD A VESSEL, AND SHALL BE CALCULATED BY DIVIDING THE LOADED QUANTITY BASIS THE STOWAGE PLAN OF PERFORMING VESSEL AT 14M DRAFT COMPRISING A CARGO BY THE APPLICABLE LOADING/DISCHARGING RATE IDENTIFIED HEREIN. LAY-TIME SHALL TERMINATE UPON THE COMPLETION OF LOADING/UNLOADING, SUBJECT TO THE PROVISIONS HEREIN BENDS.
# #C. LAY-TIME FOR LOADING OR UNLOADING SHALL COMMENCE UPON THE EXPIRATION OF TURN TIME OR AT THE TIME WHEN THE VESSEL COMMENCES UNLOADING/LOADING WHICHEVER IS EARLIER. IF, AFTER BERTHING, THE VESSEL IS FOUND NOT TO BE READY IN ALL RESPECTS TO LOAD, LAY-TIME WILL NOT COMMENCE UNTIL THE VESSEL IS READY TO LOAD IN ALL RESPECTS BENDS.
# #D. IF THE VESSEL TENDERS N.O.R. PRIOR TO THE AGREED LAYCAN AT LOAD PORT, CHARTERER IS NOT OBLIGATED TO BERTH THE VESSEL OR COMMENCE LOADING OR FOR LAYTIME TO COMMENCE TO COUNT UNTIL TWELVE (12) HOURS AFTER 00:00 HOURS ON THE AGREED LAYCAN (IE, THE FIRST DAY OF THE LAY-CAN) UNLESS SOONER COMMENCED IN WHICH CASE ACTUAL TIME USED TO COUNT, UNLESS OTHERWISE MUTUALLY AGREED BY THE PARTIES.
# #E. IF THE VESSEL TENDERS N.O.R. AFTER THE AGREED LAYCAN AT LOAD PORT AND CHARTERERS DO NOT EXERCISE THEIR OPTION TO CANCEL THE SHIPMENT IN QUESTION, LOADING SHALL BE SUBJECT TO THE AVAILABILITY OF BERTH AND CARGO AND LAYTIME TO COMMENCE FROM LOADING COMMENCEMENT.

# #F. TIME LOST BY ANY CAUSE SHALL COUNT AS LAYTIME EXCEPT IN THE CIRCUMSTANCES ENUMERATED IN THIS CONTRACT, AND SPECIFICALLY AS ENUMERATED IN ARTICLE 25, AND IN THE CASE OF A FORCE MAJEURE EVENT AND PROVIDED ALWAYS THAT A VALID DECLARATION OF A FORCE MAJEURE EVENT HAS BEEN GIVEN BY THE RELEVANT PARTY.  IF A VESSEL IS ON DEMURRAGE AT THE TIME OF A FORCE MAJEURE EVENT, TIME SHALL CEASE TO COUNT DURING THE OCCURRENCE AND CONTINUANCE OF THE FORCE MAJEURE EVENT.  IN THE CASE WHERE A FORCE MAJEURE EVENT SHALL OCCUR OUTSIDE OF ORDINARY OFFICE HOURS, NOTICE OF THE EVENT MAY BE GIVEN BY THE SHIPPER’S REPRESENTATIVE TO THE SHIP OWNER’S REPRESENTATIVE AT THE LOADING PORT AND SUCH NOTICE SHALL BE DEEMED VALID FROM THE TIME GIVEN PROVIDED THAT SUCH NOTICE IS CONFIRMED AS SOON AS PRACTICABLE ON THE NEXT BUSINESS DAY

# 25.	THE FOLLOWING SHIFTING TIME, STOPPAGES AND/OR INTERRUPTIONS TO LOADING SHALL NOT COUNT AS LAY-TIME, EVEN IF ON DEMURRAGE AT LOAD AND/OR DISCHARGE PORT-
# #
# #I.	TIME SPENT MOVING THE VESSEL FROM ANCHORAGE TO BERTH SHALL NOT COUNT AS LAY-TIME IF THE VESSEL HAS BEEN ORDERED BY THE PORT AUTHORITIES TO WAIT FOR THE BERTH BENDS.
# #II.	TIME FOR COMPLETION OF PRATIQUE, CUSTOMS CLEARANCE, OR IMMIGRATION CLEARANCE AFTER BERTHING BENDS.
# #III.	DOWNTIME TIME DUE TO BREAKAGE AND/OR REPAIR OF THE VESSEL’S EQUIPMENT, OR ANY OTHER INABILITY OF THE VESSEL TO LOAD THE CARGO AT THE AGREED LOADING RATE OR THE RESPECTIVE TERMINAL LOADING RATE WITHIN THE LAY-TIME ALLOWED BENDS.
# #IV.	IF THE CAPTAIN OF THE VESSEL DECIDES TO WARP OR SHIFT THE VESSEL AFTER IT HAS BERTHED ALONGSIDE THE WHARF FOR ANY REASON OTHER THAN THE REQUEST, ORDER OR RECOMMENDATION BY CHARTERER OR THE LOADING PORT, THE TIME REQUIRED FOR THE WARPING OR SHIFTING BENDS.
# #V.	ANY TIME LOST DUE TO THE OWNER OF THE VESSEL OR ANY GOVERNMENTAL AUTHORITY PROHIBITING THE VESSEL FROM ENTERING THE LOADING PORT OR PREVENTING, IMPEDING OR PROHIBITING LOADING IN ANY WAY.
# #VI.	ANY TIME LOST DUE TO ANY LABOR DISPUTE, STRIKE, GO SLOW, WORK TO RULE, LOCKOUT, STOPPAGE OR RESTRAINT OF LABOR INVOLVING THE MASTER, OFFICERS OR CREW OF THE VESSEL BENDS.
# #VII.	 ANY TIME LOST DUE TO NON-COMPLIANCE WITH STATUTORY AND CLASS REQUIREMENTS FOR THE VESSEL BENDS.
# #VIII.	FOR DELAYS IN LOADING THE COAL DUE TO THE VESSEL NOT COMPLYING WITH STEVEDORING REGULATIONS RELEVANT TO THE OPERATION OF THE LOADING PORT.
# #IX.	IN THE EVENT OF WEATHER CONDITIONS (INCLUDING, BUT NOT LIMITED TO SEA CONDITIONS/SWELL/FOG/WIND) WHICH, IN THE REASONABLE OPINION OF EITHER THE LOADING PORT OR THE MASTER OF THE VESSEL, MAKE LOADING UNSAFE, AND WHERE THE MASTER REFUSES TO LOAD WHEN THE LOADING PORT PREPARED TO LOAD.
# #X.	ANY TIME LOST DUE TO INEFFICIENCY OR ANY OTHER CAUSE ATTRIBUTABLE TO THE VESSEL, HER MASTER, HER CREW, OR HER OWNERS WHICH AFFECTS THE BERTHING AND LOADING/UNLOADING OF THE VESSEL.
# #XI.	ANY TIME LOST IF LOADING IS INTERRUPTED DUE TO INSUFFICIENT BALLAST PUMP CAPACITY IN RELATION TO THE LOADING RATE (IF SUCH INTERRUPTION CONTINUES FOR MORE THAN THREE (3) HOURS CHARTERER OR ITS AGENTS HAVE THE RIGHT TO ORDER THE VESSEL TO VACATE THE PIER/BERTH AND SHIFT FROM AND BACK TO THE BERTH AT OWNER'S TIME AND EXPENSE).
# #XII.	REPOSITIONING OF THE VESSEL DUE TO ITS SIZE/DIMENSIONS OR OBSTRUCTIONS IN OR ON THE VESSEL, WHICH PROHIBIT THE FREE MOVEMENT OF SUPPLIER'S LOADING AND/OR TRIMMING APPARATUS, OR CONSIGNEE'S DISCHARGING/TAKEAWAY APPARATUS.
# #XIII.	ANY TIME LOST IN TRIMMING, WHILE SHIPPER/CHARTERERS WAIT FOR MASTER'S INSTRUCTIONS, SHALL NOT COUNT AS LAY-TIME OR TIME ON DEMURRAGE.
# #XIV.	ANY EXTRA TRIMMING AND OR LEVELING OF THE CARGO REQUIRED BY MASTER OR OWNER (OR NECESSARY ON ACCOUNT OF VESSELS CONSTRUCTION) OVER AND ABOVE THAT WHICH IS CUSTOMARY AT THE LOADING FACILITY; ANY COSTS INCURRED FOR SAME TO ALSO BE FOR OWNER'S ACCOUNT.
# #XV.	TIME USED FOR REPAIRING STEVEDORE DAMAGE.
# #XVI.	FIRST OPENING AND LAST CLOSING OF HATCHES.
# #XVII.	DURING STATUTORY HOLIDAYS, AS DEFINED IN THE LOADING/UNLOADING PORT RULES AND REGULATIONS, UNLESS USED, IN WHICH CASE, ACTUAL TIME USED TO COUNT.
# #XVIII.	ANY TIME LOST IF LOADING/UNLOADING IS INTERRUPTED BY THE VESSEL IN ORDER TO CONDUCT BUSINESS ON BEHALF OF THE OWNER INCLUDING, BUT NOT LIMITED TO, TIME SPENT IN OBTAINING A DRAFT SURVEY CHECK OR THE FINAL DRAFT SURVEY AFTER COMPLETION OF LOADING AND TRIMMING; AND
# #XIX.	      NOTWITHSTANDING THE DECLARATION OF A FORCE MAJEURE EVENT, LOADING INTERRUPTIONS OR STOPPAGES INCLUDING MECHANICAL OR ELECTRICAL DELAYS, SHALL BE LIMITED TO A MAXIMUM OF FOUR (4) HOURS PER VOYAGE PER VESSEL. ON A CUMULATIVE BASIS, ANY INTERRUPTION PERIOD IN ADDITION TO THIS FOUR (4) HOUR LIMITATION SHALL COUNT AS LAYTIME.  WHEN THE VESSEL IS ON DEMURRAGE, ALL TIME LOST SHALL COUNT AS LAYTIME INCLUDING BUT NOT LIMITED TO LOADING INTERRUPTION.
# ##25.1. 	IN THE EVENT OF ANY STOPPAGE OR STOPPAGES ARISING FROM ANY CAUSE AND CONTINUING FOR A PERIOD OF SIX (6) RUNNING DAYS AT ANY TIME AFTER THE VESSEL IS READY TO LOAD/UNLOAD, OWNER AND CHARTERER SHALL CONSULT ON REMEDIAL MEASURES BENDS.
#    ##25.2 LAY-TIME SHALL CEASE TO COUNT AT THE POINT OF TIME WHEN           THE LOADING/UNLOADING HAS BEEN COMPLETED PER STEVEDORE’S LOG BENDS.
# ##25.3 LAY-DAYS SHALL BE WEATHER WORKING DAYS OF TWENTY-FOUR (24) CONSECUTIVE HOURS INCLUDING SATURDAYS AND SUNDAYS, BUT EXCLUDING STATUTORY HOLIDAYS AS DEFINED IN THE LOADING/DISCHARGING PORT RULES AND REGULATIONS BENDS.
# 26.	ALL OTHER GENERAL SHIPPING TERMS & CONDITIONS TO BE IN ACCORDANCE WITH THE LOAD PORT LOADING CONDITIONS TO APPLY.
# 27.	OWNERS SHOULD COMPLY WITH COVID 19 REGULATIONS AS PER PORT REGULATION AND TAKE APPROPRIATE STEPS AND SUITABLY NOMINATE VESSEL. NOR WILL BE ACCEPTED BOTH AT LOAD PORT AND DISCHARGE PORT (S) ONCE VESSEL IS CLEARED AND ALLOWED BY PORT AUTHORITIES FOR ENTRY.
# 28.	 OWNERS CONFIRM BELOW LOADING TERMS –
# ##A. SUPPLY OF LIGHTING AND THE OPENING OR CLOSING OF HATCH COVERS. THE VESSEL SHALL BE RESPONSIBLE FOR (AND SHALL COVER THE COST OF) FURNISHING LIGHTING NECESSARY FOR NIGHT WORK ON BOARD THE VESSEL AND FOR THE OPENING OR CLOSING OF THE HATCH COVERS BENDS.
# ##B. OWNER SHALL BEAR THE SHIPPING AGENCY, BERTHAGE, PILOTAGE, TUGBOAT AND LINE-HANDLING FEES, PORT CHARGES AND OTHER SIMILAR COSTS AND ANY TAXES, TARIFFS, DUTIES, IMPOSTS, FEES, CHARGES AND DUES OF EVERY DESCRIPTION IMPOSED OR LEVIED BY ANY GOVERNMENTAL, LOCAL OR PORT AUTHORITY BENDS.
# ##C. NO WARRANTIES OF BERTH. OWNER UNDERSTANDS AND AGREES AT ALL TIMES WITH THE LOADING PORT. OWNER HAS HAD AN OPPORTUNITY TO INSPECT THE LOADING PORT AND IRREVOCABLY ACCEPTS THE LOADING PORT, WITHOUT ANY WARRANTIES OF BERTH BY CHARTERER; PROVIDED, HOWEVER, THAT NOTHING HEREIN IS INTENDED TO AFFECT THE RIGHTS BETWEEN OWNER, THE LOADING PORT, OR ITS CHARTERER.
# ##D. VESSEL SHALL SAIL FROM THE LOADING BERTH AS SOON AS THE LOADING AND SUBSEQUENT FORMALITIES ARE COMPLETED. UNLESS THE RELEVANT AUTHORITIES AUTHORIZE EXTRA DELAYS, OTHERWISE IF THE VESSEL IS PREVENTED IN LEAVING THE BERTH THROUGH FAULT OF THE OWNER AND IF THE VESSEL FAILS TO LEAVE WITHIN TWO (2) HOURS OF COMPLETION OF LOADING FOR ANY REASONS ATTRIBUTABLE TO HER, ANY LOSS OF TIME AND/OR EXPENSES (DIRECT/INDIRECT) INCURRED BY ANY PARTY RESULTING THEREFROM TO BE FOR OWNER'S ACCOUNT. REFUELING CAN ONLY OCCUR AFTER LOADING IS COMPLETED.

# 29.	FREIGHT:  USD ____ PMT FIOST - GOA BERTH NO. 6 OR BERTH NO.7

# ## BASE FREIGHT RATE IS TAKEN BSS GOA BERTH 6 OR 7 FREE PDA DISCH PORT (PDA +ILH+ AGENCY FEE TO BE ON CHARTERERS A/C).

# ## FOR ONLY ENNORE PORT DISCHARGE, THE FREIGHT WILL BE USD 0.60 MORE THAN GOA BERTH 6 FREIGHT IF EXERCISED.

# ## FOR ONLY KRISHNAPATNAM PORT DISCHARGE, THE FREIGHT WILL BE USD 0.70 MORE THAN GOA BERTH 6 FREIGHT IF EXERCISED

# ## FOR ONLY PARADIP PORT DISCHARGE, THE FREIGHT WILL BE USD 1.20 MORE THAN GOA BERTH 6 FREIGHT IF EXERCISED.

# ## FOR ONLY JAIGARH DISCHARGE, THE FREIGHT WILL BE USD 0.10 MORE THAN GOA B6 FREIGHT IF EXERCISED.

# ## FOR ONLY NEW MANGALORE PORT DISCHARGE, THE FREIGHT WILL BE USD 0.20 LESS THAN GOA B6 FREIGHT IF EXERCISED.

# ## FOR ONLY ENNORE AND PARADIP (BSS 1:2) PORTS DISCHARGE, THE FREIGHT WILL BE USD 1.00 MORE THAN ENNORE FREIGHT IF EXERCISED.

# ## FOR ONLY KRISHNAPATNAM AND PARADIP (BSS 1:2) PORTS DISCHARGE, THE FREIGHT WILL BE USD 1.00 MORE THAN KRISHNAPATNAM FREIGHT IF EXERCISED.

# ## FOR ONLY KRISHNAPATNAM AND GANGAVARAM (BSS 1:2) PORTS DISCHARGE, THE FREIGHT WILL BE USD 0.60 MORE THAN KRISHNAPATNAM FREIGHT IF EXERCISED.


# ## FOR ONLY PARADIP AND ENNORE (BSS 1:2) PORTS DISCHARGE, THE FREIGHT WILL BE USD 1.00 MORE THAN PARADIP FREIGHT IF EXERCISED. (NOTE- FOR PARADIP AND ENNORE PORTS DISCHARGE, FIRST DISCHARGE PORT TO BE PARADIP AND SECOND PORT TO BE ENNORE). (IF PARADIP IS EXERCISED AS 1ST OR 2ND DISPORT BSS 1:2, THEN TENTATIVE QUANTITY BIFURCATION FOR PARADIP WOULD BE APPROX 20K TO 40K MTS).

# ## FOR ONLY JAIGARH AND GOA 6 OR 7 (BSS 1:2) PORTS DISCHARGE, THE FREIGHT WILL BE USD 0.30 MORE THAN JAIGARH FREIGHT IF EXERCISED.

# ## ANY OTHER DISPORT TO BE DISCUSSED ON OPEN BOOK BASIS.

# ## ANY ADDITIONAL QUANTITY LOADED MORE THAN CONTRACTUAL QUANTITY, FREIGHT FOR ADDITIONAL QUANTITY TO BE APPLICABLE 50% OF THE AGREED FREIGHT RATE.

# ## IT IS UNDERSTOOD THAT FREIGHT IS INCLUSIVE OF ADDITIONAL WAR RISK PREMIUM, DEVIATION COST, KIDNAP AND RANSOM, ARMED GUARDS AND OTHER RELATED COST.


# ## ROUTING IN OWNERS OPTION AND FREIGHT RATE REMAINS SAME AS PER AGREED ABOVE, REGARDLESS OF ANY ROUTE CHOSEN BY THE OWNERS TO PERFORM THE FIXTURE. OWNER TO DECLARE LADEN ROUTING VIA COGH OR VIA SUEZ CANAL, LATEST UPON COMPLETION OF LOADING.

# 30.	OWNERS TO SATISFY THEMSELVES WITH PORT AND DRAFT RESTRICTIONS AND CONFIRM COMPLIANCE BOTH ENDS. DEAD FREIGHT APPLICABLE BASIS 14M SW DRAFT IRRESPECTIVE OF RESTRICTIONS BENDS.
# 31.	DEMM / DESP:  USD ______ PDPR HD WTS BENDS.
# ## ALLOWABLE LAY-TIME SHALL BE CALCULATED BY DIVIDING THE LOADED QUANTITY BASIS THE STOWAGE PLAN OF PERFORMING VESSEL AT 14M DRAFT COMPRISING A CARGO BY THE APPLICABLE LOADING/DISCHARGING RATE.  ALLOWABLE LAY TIME SHALL BE EXPRESSED TO THE FIFTH DECIMAL PLACE, WITH THE SIXTH DECIMAL PLACE BEING ROUNDED UP IF FIVE OR GREATER AND ROUNDED DOWN OTHERWISE.
# #DESPATCH MONEY SHALL BE PAID BY OWNER TO CHARTERERS FOR LAYTIME SAVED AT THE RATES OF ONE-HALF (1/2) OF THE APPLICABLE DEMURRAGE RATES.

# 32.	100 PCT FRT TO BE PAID WITHIN 25 B/DAYS AFTER COMPLETION OF LOADING, RELEASING BILLS OF LADING, ALWAYS BEFORE BREAKING BULK.
# ## LOAD PORT /DISCHARGE PORT DEMURRAGE/DESPATCH WHICH TO BE SETTLED WITHIN 60 DAYS OF AGREEMENT OF OWNERS LAYTIME.
# ## OWNERS TO PROVIDE LAYTIME STATEMENT WITHIN 15 DAYS OF VESSEL LOADING/ DISCHARGING.
# ## IF FREIGHT PREPAID BILL(S) OF LADING IS REQUIRED THEN SAME TO BE RELEASED UPON RECEIPT OF THE FULL FREIGHT PAYMENT FROM CHARTERERS.
# ## FREIGHT DEEMED TO BE EARNED AND NON-RETURNABLE WHETHER CARGO AND OR SHIP LOST OR NOT LOST.
# ## OWNERS AGREE TO RECEIVE THE FREIGHT FROM SHIPPER; CHARTERERS REMAIN FULLY RESPONSIBLE FOR PAYMENT OF FREIGHT.
# ## ORIGINAL CHARTER PARTY DULY SIGNED AND STAMPED BY OWNERS MUST REACH CHARTER’S OFFICE FOR REMITTING FREIGHT.
# 33.	OWNERS/DISPONENT OWNERS TO BE OF COUNTRY HAVING DUAL TAXATION AGREEMENT WITH INDIA. ATTACHED CERTIFICATE TO BE FILLED AND RETURNED UPON FIXING MAIN TERMS.
# OWNERS TO APPOINT CHRTRS NOMINATED AGENTS BOTH AT LOAD PORT AND DISCHARGE PORT AND OWNERS TO PAY FOR ALL THE CHARGES AT LOAD PORT BOTH ENDS.
# ## CHARTERERS WILL HAVE THE OPTION TO PAY THE PDA AT DISCHARGE PORT (INCLUDING AGENCY FEE AND ILH) AND PORT LIGHTERAGES CHARGES AFTER DULY APPROVED BY THE OWNERS AND THE SAME WILL BE DEDUCTED FROM THE 100% FREIGHT PAYMENT.

# ## FINAL PDA WILL BE SETTLED ALONG LOAD PORT /DISCHARGE PORT DEMURRAGE/ DESPATCH AMOUNT SUBJECT TO FINAL PORT BILL DULY APPROVED BY OWNERS.

# ## CHARTERERS WILL NOT BE ABLE TO PROVIDE ORIGINAL PORT / AGENCY BILL S AS THE SAME IS REQUIRED FOR AVAILING SERVICE TAX OR GST BENEFIT.

# 34.	TAXES /DUES ON CARGO CHRTRS A/C AND ON FRT/VSL TO BE FOR OWNERS A/C AT EACH PORT. ALL VESSELS CHARGES PERTAINING TO GRT/NRT OF THE VESSEL WILL BE ON OWNERS ACCOUNT.

# 35.	LAYTIME / DEMURRAGE SHALL CEASE TO COUNT UPON COMPLETION LOADING/ DISCHARGING OPERATIONS.

# 36.	LAYTIME NON-REVERSIBLE BETWEEN LOAD / DISCHARGE PORT.

# 37.	INITIAL, INTERMEDIATE AND FINAL DRAFT SURVEY/DRAFT CHECK   NOT TO COUNT AS LAYTIME AT EACH PORT, EVEN IF ON DEMURRGE. TIME NOT TO COUNT FOR GANGWAY DOWN/HATCH INSPECTION/MEDICAL FORMALITIES/PHO FORMALITIES / QURANTINE INSPECTION/ ETC BENDS EVEN IF VESSEL IS ON DEMURRAGE.

# 38.	FIRST OPENING AND LAST CLOSING OF HATCHES NOT TO COUNT AS LAYTIME AT EACH PORT, EVEN IF VESSEL IS ON DEMURRAGE.

# 39.	DURING PERIODS WHEN SENIOR VESSELS ARE ENGAGED IN LOADING OR DISCHARGING OPERATIONS AND ARE IMPACTED BY ADVERSE WEATHER CONDITIONS, THE TIME LOST DUE TO SUCH WEATHER SHALL NOT BE COUNTED AS LAYTIME FOR VESSELS WAITING FOR   LOADING/DISCHARGING SUBJECT TO PROVIDING THE SUPPORTING DOCUMENTS

# 40.	SHIFTING TIME FROM ANCHOR AWAY OR PILOT ON BOARD WHICH EVER IS EARLIER TILL ALL FAST IN BERTH / ANCHORAGE NOT TO COUNT AS LAYTIME AT EACH PORT, EVEN IF VESSEL IS ON DEMURRAGE.  SHIFTING TIME AND COST UPTO TWO SHIFTING WILL ALWAYS BE ON OWNERS ACCOUNT, EVEN IF ON DEMURRAGE.

# 41.	TIME USED FOR VESSEL FORMALITIES / CUSTOMS FORMALITIES / PORT REQUIREMENT NOT TO COUNT AS LAYTIME AT EACH PORT, EVEN IF VESSEL IS ON DEMURRAGE.

# 42.	FOLLOWING WILL NOT COUNT AS LAYTIME BENDS EVEN IF VESSEL IS ON DEMURRAGE.
# A.	CHAMBER OF COMMERCE (CHARTER PARTY HOLIDAYS).
# B.	BIMCO HOLIDAYS.
# C.	PORT HOLIDAYS (WHETHER PORT IS WORKING OR NOT)
# D.	NO ACTIVITY BEING CARRIED OUT ON VESSEL IN PARTICULAR PORT DUE TO HOLIDAY AS SPECIFIED IN POINT A, B, AND C (WHETHER VESSEL IS ON BERTH OR WAITING).
# E.	IF TIME USED THEN ONLY ACTUAL TIME USED TO COUNT AS LAYTIME.

# 43.	VESSEL ON ARRIVAL LOADPORT TO HAVE ALL HOLDS AND HATCHES/HATCH COVERS CLEAN-SWEPT, CLEAR, WASHED AND DRIED, FREE OF LOOSE RUST FLAKES/SCALES AND RESIDUES AND/OR ODORS OF PREVIOUS CARGO (ES)/GAS FREE CONDITION AND IN EVERY WAY BE READY AND SUITABLE TO LOAD COAL IN BULK TO INDEPENDENT SURVEYOR’S/SHIPPER SATISFACTION, SHOULD VESSEL BE REJECTED BY SURVEYOR, THEN NOR WILL BE INVALID AND WILL ONLY BECOME VALID AFTER VESSEL IS DEEMED TO BE CLEANED AND READY IN ALL ASPECTS TO LOAD BY CHARTERERS (OR ITS SURVEYORS), PROVIDED ALL OTHER TENDERING CONDITIONS HAVE BEEN MET. LAYTIME IS TO THEN TO COUNT PURSUANT TO THE TERMS SET FORTH IN THIS AGREEMENT. ANY DIRECTLY RELATED EXPENSES INCURRED TO BE FOR OWNER'S ACCOUNT.

# 44.	GA & ARBITRATION IN LONDON AND ENGLISH LAW TO APPLY

# 45.	ANY DISPUTES REGARDING STEVEDORES DAMAGE TO THE VESSEL TO BE SETTLED DIRECTLY BETWEEN OWNERS AND STEVEDORES AND ANY ADDITIONAL TIME OCCUPIED IN REPAIRING DAMAGE NOT TO COUNT AS LAYTIME PROVIDED SAME DOES NOT AFFECT CARGO WORKING AND SEAWORTHINESS.  MASTER TO NOTIFY AGENTS AND STEVEDORES IN WRITING WITHIN 24 HOURS AFTER OCCURRENCE, EXCEPT IN CASE OF HIDDEN DAMAGES. IF OWNERS SHOULD NOT BE ABLE TO SETTLE CLAIMS DIRECTLY, CHARTERERS TO MAKE BEST EFFORT TO ASSIST OWNERS TO RECOVER SAME FROM STEVEDORES WITHOUT ANY RESPONSIBILITY.

# 46.	LETTER OF INDEMNITY CLAUSE
#              IN CASE ORIGINAL BS/L IS NOT AVAILABLE ON ARRIVAL AT DISPORT THEN             OWNERS/MASTER TO AGREE TO DISCHARGE AND DELIVER THE CARGO W/O DELAY AGAINST CHTRS LOI BASED ON OWNRS PNI CLB STANDARD WORDING BUT SIGNED BY CHRTRS ONLY IN CHARTERERS OFFICIAL   LETTER HEAD.

# 47.	INSURANCE & P & I
# THE OWNERS GUARANTEE THAT M.V. _____ HAS FULL MARINE INSURANCE COVER FOR HULL AND MACHINERY AND FULL PROTECTION AND INDEMNITY (P&I) COVER WITH AN INTERNATIONAL GROUP OF P&I CLUB WHICH WILL BE MAINTAINED UNTIL COMPLETION OF DISCHARGE.
#              #P&I IS PRESENTLY WITH ____________________.

# 48.	OVERTIME CLAUSE
# OVERTIME TO BE THE ACCOUNT OF PARTY ORDERING IT.  HOWEVER, OFFICERS AND CREW OVERTIME TO BE ALWAYS ON OWNERS ACCOUNT.  OVERTIME, IF ORDERED BY PORT AUTHORITIES, SAME TO BE FOR CHARTERERS/ RECEIVERS/ SHIPPERS ACCOUNT.  IT IS CLEARLY UNDERSTOOD THAT ANY WATCHMEN REQUIRED FOR CARGO AT LOAD / DISCHARGE PORT (S) TO BE ALWAYS ON ACCOUNT OF CHARTERERS.

# 49.	FORCE MAJEURE
# # FORCE MAJEURE EVENT SHALL NOT COUNT AS LAYTIME EVEN IF VESSEL IS ON DEMURRAGE.

# ## THE TERM " FORCE MAJEURE" SHALL MEAN ANY CAUSE BEYOND REASONABLE CONTROL AND WITHOUT FAULT OR NEGLIGENCE OF THE AFFECTED PARTY WHICH WHOLLY OR IN SUBSTANTIAL PART PREVENTS THE PRODUCTION, LOADING, DISCHARGING OR DELIVERY OF THE PRODUCT UNDER CARRIAGE, HEREUNDER.

# ## FORCE MAJEURE SITUATIONS INCLUDE BUT ARE NOT LIMITED TO ACTS OF THE PUBLIC ENEMY, ACTS OF WAR, RIOT OR CIVIL COMMOTION, TERRORISM, ACCIDENTS, FIRES, EXPLOSIONS, FLOODS, ACTS OF GOD, OTHER NATURAL CALAMITIES, PARTIAL OR COMPLETE EMBARGOES, INTERRUPTION OF CONTINGENCIES OR TRANSPORTATION, ACTS OF GOVERNMENT AUTHORITIES, ACTS, RULES, REGULATIONS OF ANY GOVERNMENT.

# ## PARTY INVOKING FORCE MAJEURE SHALL GIVE PROMPT WRITTEN NOTICE (WITHIN 14 DAYS) TO THE OTHER PARTY INDICATING THE DETAIL AND NATURE OF THE FORCE MAJEURE SITUATION.  IF ANYONE OCCURRENCE OF FORCE MAJEURE CONTINUES UNINTERRUPTED FOR 30 DAYS OR MORE, OWNERS / CHARTERERS MAY OPT TO CANCEL THIS AGREEMENT WITHOUT ANY WAY, BEING LIABLE TO THE OTHER PARTY FOR SUCH CANCELLATION.

# ## DELIVERY SHALL BE RESUMED BY PARTY/ PARTIES AFTER CESSATION OF FORCE MAJEURE.

# 50.	ARBITRATION
# IN CASE OF ANY DISPUTE NOT SETTLED BETWEEN THE TWO PARTIES MUTUALLY BY NEGOTIATION, MATTER TO BE DECIDED BY ARBITRATION IN LONDON BASED ON THE ENGLISH LAW.  EACH PARTY TO APPOINT THEIR OWN ARBITRATOR.  IN AN EVENT OF ARBITRATORS FAILING TO REACH UNANIMOUS DECISION, THEY ARE TO APPOINT AN UMPIRE.  THE UMPIRE'S DECISION SHALL BE BINDING ON BOTH PARTIES.

# 51.	ADDITIONAL CLAUSES

# #A.	THE FULL FREIGHT IS DEEMED EARNED UPON SHIPMENT AND COMPLETION OF LOADING, SHIP/OR CARGO LOST OR NOT LOST.

# #B.	OWNERS TO ENSURE AND GUARANTEE THAT THE VESSEL'S HATCH COVERS ARE WEATHER TIGHT.

# #C.	ALL STOPPAGES CAUSED BY THE VESSEL DUE TO BALLASTING/DE-BALLASTING, WILL NOT COUNT AS LAYTIME, EVEN ON DEMURRAGE.

# #D.	OWNERS CONFIRM HATCHES WILL NOT BE OPENED DURING TRANSIT AND WILL BE OPENED AT DISCHARGE PORT(S) ONLY.

# #E.	OPENING AND CLOSING OF HATCHES WILL ALWAYS BE DONE BY VESSEL'S CREW AND COST AND TIME TO OWNERS ACCOUNT.

# #F.	DURING LOADING/DISCHARGING, CHARTERERS ARE PERMITTED TO PLACE STEVEDORES ON BOARD THE VESSEL AND OWNERS TO PROVIDE FOR THEIR NORMAL FRESH WATER NEEDS FOR COOKING ETC., WITHOUT ANY COST TO CHARTERERS

# #G.	OWNERS TO ARRANGE TO DISCHARGE FULL AND COMPLETE QUANTITY AT (DISCHARGE PORT) AS PER BILLS OF LADING QUANTITIES.

# #H.	DURING LOADING/ DISCHARGING OPERATION, ANY DISRUPTION DUE TO BAD WEATHER AND ROUGH SEA TIME NOT TO COUNT OR DEDUCTED PRORATA UNLESS VESSEL IS ON DEMURRAGE.


# 52.	GENERAL AVERAGE CLAUSE: GENERAL AVERAGE / ARBITRATION IF ANY TO BE HELD IN LONDON & ENGLISH LAW TO APPLY.




# 53.	BIMCO ISPS CLAUSE: OWNERS TO INCORPORATE BIMCO ISPS CLAUSE FOR VOYAGE CHARTER PARTIES

# 54.	SWITCH B/L: CHARTERERS ARE ALLOWED TO CHANGE THE DISCH PORT(S) WITHIN INDIA AND/OR NOTIFY PARTY AND/OR TO ORDER PARTY AND/OR SHIPPERS NAMED IN THE ORIGINAL BILLS OF LADING IN ORDER TO COMPLY WITH THE LETTER OF CREDIT PROVIDED THE FIRST COMPLETE SET OF THE ORIGINAL BILLS OF LADING ARE DELIVERED TO OWNER OR OWNER’S AGENT IN SINGAPORE. THE 1ST SET OF BS/L’S ARE TO BE MARKED NULL AND VOID AND SHOULD BE RETURNED TO OWNER TOGETHER WITH LOI IN OWNER'S P&I WORDING SIGNED BY AUTHORISED PERSON FROM CHARTERERS’ OFFICE. CHARTERER TO PROVIDE A DRAFT COPY OF THE SECOND SET OF B/L FOR OWNERS APPROVAL. NEW SET (2ND SET OF BLS), WHICH WILL BE THE FINAL BL’S UNDER THE OWNER'S (OR OWNERS NOMINATED AGENTS) APPROVAL WILL BE ISSUED AND CHARTERERS TO PROVIDE THEIR LOI IS ACCEPTED/APPROVED BY OWNERS.  IN SUCH CIRCUMSTANCES DISCHARGE AGAINST THE  1ST B/L WILL BE FORBIDDEN AND SAID 1ST B/L OR BS/L WILL NOT BE PRESENTED AT DISCHARGE PORT TO AGENTS OR CUSTOMS OFFICIALS. IN ANY CASE, NO TWO SETS OF B/L SHOULD EXIST AT THE SAME TIME. ALL SUCH SWITCHING TO BE DONE BBB.


# 55.	UPON FIXING MAIN TERMS OWNERS TO PROMPTLY FAX / MAIL TO CHRTRS THE FOLLOWING CERTIFICATES FOR APPLICATION OF REQUISITE PERMISSIONS FROM THE COMPETENT INDIAN AUTHORITIES:

#       #A. VESSELS REGISTRY
#       #B.  CLASS CERTIFICATE
#       #C. INTERNATIONAL TONNAGE CERTIFICATE
#       #D. INTERNATIONAL SAFETY EQUIPMENT CERTIFICATE
#       #E. INTERNATIONAL SAFETY CONSTRUCTION CERTIFICATE
#       #F. INTERNATIONAL RADIO-TELEPHONY CERTIFICATE
#       #G.  INTERNATIONAL OIL POLLUTION PREVENTION CERTIFICATE
#       #H.  SAFE MANNING CERTIFICATE
#       #I.  DOCUMENT OF COMPLIANCE CERTIFICATES
#       #J.   P & I CLUB CERTIFICATE
#       #K.  INTERNATIONAL LOAD LINE CERTIFICATE
#       #L. ISPS CERTIFICATE
#       #M.  SAFETY MANAGEMENT CERTIFICATE
#       #N.  INTERNATIONAL SEWAGE POLLUTION PREVENTION CERTIFICATE
#       #O.  INTERNATIONAL AIR POLLUTIO PREVENTION CERTIFICATE
#       #P.  LRIT CONFORMANCE TEST REPORT
#       #Q. CERTIFICATE OF TAX ASSESSMENT FOR THE FREIGHT BENEFICIARY
#               FROM THE   COUNTRY OF DOMICILE
#       #R. GAS FREE CERTIFICATE

# 56.	DETAILS OF PARTY FOR REMITTANCE
#  FOLLOWING INFORMATION / DOCUMENTS REQUIRED IN CASE OF PAYMENTS MADE TO
#  FOREIGN/ NON-RESIDENT COMPANIES AS WELL AS NRIS:

# #I.        NAME OF THE PARTY
#  #II.        FULL ADDRESS OF THE PARTY
#  #III.        PAN OF PARTY – IF ANY
#  #IV.        PRINCIPAL PLACE OF BUSINESS
#  #V.        COUNTRY TO WHICH REMITTANCE IS MADE
#  #VI.        (ISD CODE)- PHONE NUMBER OF PARTY
#  #VII.        EMAIL ADDRESS OF PARTY
#  #VIII.        STATUS OF THE PARTY
#  		# A) COMPANY
# 		# B) OTHER THAN COMPANY
#  #IX.        AMOUNT OF REMITTANCE ( IN FOREIGN CURRENCY)
#  #X.       TAX RESIDENCY CERTIFICATE OF THE PARTY
#  #XI.        BRIEF OF NATURE OF SERVICES PROVIDED BY THE PARTY
#  #XII.        WHETHER SUCH SERVICE IS BEING PROVIDED IN INDIA OR OUT OF INDIA?
#  		# A) IN INDIA
#        	# B) OUTSIDE INDIA
#  #XIII.       CONFIRMATION FROM THE PARTY THAT THEY DO NOT HAVE ANY BRANCH OFFICE
#              	# A) IN INDIA.
# # B) OUTSIDE INDIA
# #XIV.      IF NOT HAVING ANY BRANCH OFFICE, WHETHER ANY FULL-FLEDGED AGENT OF SUCH COMPANY OPERATES FROM INDIA?

# #XV. WHETHER AS PER AGREEMENT/ TERMS OF SERVICE, TAX IS TO BE BORNE BY PARTY OR JSW STEEL LIMITED?
#  ##YES
#  ##NO

# 57.	NIL ADDRESS COMMISSION TO CHARTERERS.

# 58.	ONCE VESSEL IS FULLY FIXED OWNERS TO PROVIDE CLEAN FIXTURE RECAP WITH C/P DATED ON THEIR LETTER HEAD DULY SIGNED AND STAMPED TO CHARTERERS BY COURIER IMMEDIATELY.

# 59.	CHARTRS APPROVAL 24 HRS AFMT.
# SUBJECT TO CHARTERER’S / SHIPPER’S / TERMINAL’S ACCEPTANCE WITHIN 48 HOURS OF NOMINATION OF PERFORMING VESSEL SUBJECT TO PROVIDING ALL THE NECESSARY CERTIFICATES / DOCUMENTS REQUIRED.

# 60.	SUB REVIEW OF CHRTRS EXECUTED CP FOR SIMILAR BIZ.

# 61.	OWNERS/OPERATORS TO NOMINATE A NON - CHINESE BUILT VESSEL. IN CASE OWNERS/OPERATORS FAIL TO DO SO, AND UNLESS CHARTERERS AT THEIR OPTION AGREE TO PAY SUCH CHARGES ON AN OPEN BOOK BASIS (ALONG WITH SUPPORTINGS), EITHER PARTY SHALL HAVE THE RIGHT TO TERMINATE THIS FIXTURE. CHARTERERS TO CONFIRM VESSEL ACCEPTANCE/REJECTION WITHIN 48 HOURS AND IF ACCEPTED, IT IS DEEMED THAT CHARTERERS ALSO ACCEPT THE OPTION TO BEAR SUCH ADDITIONAL CHARGES.

# 62.	JSW STEEL LIMITED SHALL AT ITS SOLE DISCRETION RESERVE THE RIGHTS TO ASSIGN, TRANSFER, NOVATE, OR SIGN THE CONTRACT IN FAVOUR OF ITS NOMINEE/SUBSIDIARY/AFFILIATE/GROUP COMPANIES/SUPPLIER. IN CASE THE BIDDER IS SHORTLISTED AND AWARDED THE CONTRACT, THE DEFINITIVE AGREEMENT MAY BE SIGNED BY JSW STEEL LIMITED OR ANY OF ITS NOMINEE/AFFLIATE/GROUP COMPANY/SUPPLIER WHICH THE BIDDER EXPRESSLY AGREES. SIGNING OF DEFINITIVE AGREEMENT WITH NOMINEE/SUBSIDIARY/AFFILIATE/GROUP COMPANIES/SUPPLIER OF JSW WILL ESTABLISH INDEPENDENT CONTRACTUAL RELATIONSHIP BETWEEN THE SHORTLISTED BIDDER AND SUCH JSW NOMINEE/SUBSIDIARY/AFFILIATE/GROUP COMPANIES/SUPPLIER AND DEEMED TO SUBSTITUTE AND RELEASE JSW STEEL LIMITED.


# ## THE SHORTLISTED BIDDER RAISES ITS INVOICES AGAINST SUCH JSW’S NOMINEE/SUBSIDIARY/AFFILIATES/GROUP COMPANY/SUPPLIER SIGNING THE DEFINITIVE AGREEMENT AND SUCH JSW NOMINEE/SUBSIDIARY/AFFILIATE/GROUP COMPANY /SUPPLIER SHALL BE SOLELY RESPONSIBLE FOR PAYMENT OF INVOICES DIRECTLY TO THE SERVICE PROVIDER/YOU AND ENFORCE ALL THE RIGHTS UNDER THE TENDER DOCUMENT / CONTRACT / DEFINITIVE AGREEMENT.


# 63.	ANNEXURE – NOMINEES LIST

# ## AMBA RIVER COKE LIMITED
# ## BHUSHAN POWER AND STEEL LTD.
# ## BMM ISPAT LIMITED
# ## JSW CEMENT LIMITED
# ## JSW ENERGY LIMITED
# ## JSW VIJAYNAGAR METALLICS LIMITED
# ## JSW STEEL COATED PRODUCTS LIMITED
# ## JSW STEEL GLOBAL TRADE PTE LTD
# ## MITSUBISHI CORPORATION RTM INTERNATIONAL PTE LTD





# """